baseURL = 'https://www.liyanasahir.in/'
languageCode = 'en-us'
title = 'Liyana Sahir'
theme = "PaperMod"

[pagination]
  pagerSize = 20
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML =  true
  minifyOutput = true

[params]
  env = "production"
  title = "Liyana Sahir"
  description = "Liyana Sahir | AI/ML Researcher, Data Scientist, Occasional Writer"
  images = ["/media/profile_seoul.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "light"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.label]
  icon = "media/favicon-malayalam.svg"
  iconHeight = 28

[params.assets]
  favicon = "/media/favicon-malayalam.svg"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "Work"
  url = "/work/"
  weight = 10

[[menu.main]]
  name = "Writing"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Reading"
  url = "/reading/"
  weight = 25

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30


[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [["$$", "$$"]]
  inline = [["$", "$"]]