baseURL = 'https://www.liyanasahir.in/'
languageCode = 'en-us'
title = 'Blog | Liyana Sahir'
paginate = 20
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML =  true
  minifyOutput = true

[params]
  env = "production"
  title = "Liyana"
  description = "Blog | Liyana Sahir"
  images = ["/media/01.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "light"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.assets]
  favicon = "/media/logo.png"

[params.homeInfoParams]
  title = "Hi! 👋🏼"
  Content = "I'm Liyana, and this blog is a digital garden. \nEverything is an experiment - some just more thought out than others. Dip right in, maybe with a cup of chai for company?"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/liyanasahir"

[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/liyanasahir"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/liyanasahir"

[markup.goldmark.renderer]
unsafe = true