baseURL = 'https://www.liyanasahir.in/'
languageCode = 'en-us'
title = 'Liyana Sahir'
theme = "PaperMod"

[pagination]
  pagerSize = 20
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML =  true
  minifyOutput = true

[params]
  env = "production"
  title = "Liyana Sahir"
  description = "Liyana Sahir — Researcher, Data Scientist"
  images = ["/media/profile_seoul.jpg"]
  DateFormat = "January 2, 2006"
  defaultTheme = "light"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.label]
  icon = "media/profile_seoul.jpg"
  iconHeight = 28

[params.assets]
  favicon = "/media/profile_seoul.jpg"

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 10

[[menu.main]]
  name = "Writing"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Now"
  url = "/now/"
  weight = 40

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [["$$", "$$"]]
  inline = [["$", "$"]]